# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586bb74f76ca6bd1bdd7b982d73bbb2c7968f3dddb522a8dda80a5d2685e932e063e1eab0d4fdc8c2bfff04089fc0b77c8634c3bf6ddb55e201b174b28603866

test:
  secret_key_base: 7c94507e43e35c86de2fd6ed2c1eb377c348305c1a646e52fbd32eee89a4672f1d21f18828ea3b3f3fbb14becef76fec58f7811356b61937b08c35a069d1cca5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
